name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  WORKDIR: ./examples/arithmetic_progression

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Configure project
        working-directory: $WORKDIR
        run:
          - mkdir build
          - cmake -S . -B build
      - name: Build project
        working-directoyr: $WORKDIR
        run:
          - cmake --build build
      - name: Test project
        working-directory: $WORKDIR
        run:
          - ctest --test-dir build

