---
name: Main workflow

on: # yamllint disable-line
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  WORKDIR: ./examples/arithmetic_progression

jobs:
  main:
    runs-on: ubuntu-24.04
    container:
      image: sindiesel/ubuntu_24.04_test:1.1
    steps:
      - uses: actions/checkout@v4

      - name: Configure project
        working-directory: ${{ env.WORKDIR }}
        run: |
          mkdir build
          cmake -S . -B build

      - name: Build project
        working-directory: ${{ env.WORKDIR }}
        run: cmake --build build

      - name: Test project
        working-directory: ${{ env.WORKDIR }}
        run: ctest --test-dir build
